# Yahoo Finance: Daily Price Bars
1. Install yfinance: pip install yfinance
2. Documentation: https://pypi.org/project/yfinance/
3. GitHub: https://github.com/ranaroussi/yfinance

In [1]:
import yfinance as yf
import pandas as pd

In [2]:
univ = ['AAPL','MSFT','GOOG','AMZN','FB','TSLA','BRK-A','NVDA','V']
stock_px = yf.download(univ, start="2019-01-01")

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  9 of 9 completed

9 Failed downloads:
['V', 'AAPL', 'FB', 'GOOG', 'TSLA', 'NVDA', 'AMZN', 'BRK-A', 'MSFT']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

In [3]:
stock_px

Price            Close                                               \
Ticker            AAPL        AMZN     BRK-A         FB        GOOG
Date
2019-01-02   37.538818   76.956497  304057.0        NaN   51.903217
2019-01-03   33.799679   75.014000  287000.0        NaN   50.424809
2019-01-04   35.242558   78.769501  292500.0        NaN   53.136967
2019-01-07   35.164116   81.475502  295400.0        NaN   53.021824
2019-01-08   35.834446   82.829002  294300.0        NaN   53.413387
...                ...         ...       ...        ...         ...
2026-01-12  260.250000  246.470001  747860.0  42.599998  332.730011
2026-01-13  261.049988  242.600006  742300.0  42.580002  336.429993
2026-01-14  259.959991  236.649994  743438.0  42.525002  336.309998
2026-01-15  258.209991  238.179993  738691.0  42.506001  333.160004
2026-01-16  255.529999  239.119995  740750.0  42.506001  330.339996

Price                                                             High  ...  \
Ticker            MSFT        NVDA        TSLA           V        AAPL  ...
Date                                                                    ...
2019-01-02   94.612610    3.377166   20.674667  126.589890   37.759889  ...
2019-01-03   91.132004    3.173128   20.024000  122.028084   34.638787  ...
2019-01-04   95.370468    3.376423   21.179333  127.285194   35.311495  ...
2019-01-07   95.492111    3.555173   22.330667  129.580414   35.378055  ...
2019-01-08   96.184486    3.466666   22.356667  130.285187   36.088795  ...
...                ...         ...         ...         ...         ...  ...
2026-01-12  477.179993  184.940002  448.959991  343.200012  261.299988  ...
2026-01-13  470.670013  185.809998  447.200012  327.880005  261.809998  ...
2026-01-14  459.380005  183.139999  439.200012  329.170013  261.820007  ...
2026-01-15  456.660004  187.050003  438.570007  327.750000  261.040009  ...
2026-01-16  459.859985  186.229996  437.500000  328.299988  258.899994  ...

Price             Open     Volume                                     \
Ticker               V       AAPL       AMZN BRK-A      FB      GOOG
Date
2019-01-02  123.808952  148158800  159662000   400     NaN  30652000
2019-01-03  124.961407  365248800  139512000   700     NaN  36822000
2019-01-04  124.228072  234428400  183652000   800     NaN  41878000
2019-01-07  128.047086  219111200  159864000   600     NaN  39638000
2019-01-08  131.399466  164101200  177628000   300     NaN  35298000
...                ...        ...        ...   ...     ...       ...
2026-01-12  342.779999   45263800   35867800   600   700.0  23893800
2026-01-13  337.000000   45730800   38371800   300   100.0  24616700
2026-01-14  328.660004   40019400   41410600   500   300.0  17839300
2026-01-15  329.329987   39388600   43003600   300  2500.0  16424900
2026-01-16  326.779999   72018600   45824700   300   300.0  21785400

Price
Ticker          MSFT       NVDA       TSLA         V
Date
2019-01-02  35329300  508752000  174879000   8788000
2019-01-03  42579100  705552000  104478000   9428300
2019-01-04  44060600  585620000  110911500  11065800
2019-01-07  35656100  709160000  113268000  12928000
2019-01-08  31514400  786016000  105127500   9243000
...              ...        ...        ...       ...
2026-01-12  23519900  137968500   61649600  13281300
2026-01-13  28545800  160128900   53719200  20383500
2026-01-14  28184300  159586100   57259500   9388400
2026-01-15  23225800  206188600   49465800   8587700
2026-01-16  33795700  187613900   60047300   8305600

[1771 rows x 45 columns]

In [7]:
### stock_px['Adj Close']['AAPL'].plot()
stock_px.columns.names
stock_px.columns[:10]

MultiIndex([('Close',  'AAPL'),
            ('Close',  'AMZN'),
            ('Close', 'BRK-A'),
            ('Close',    'FB'),
            ('Close',  'GOOG'),
            ('Close',  'MSFT'),
            ('Close',  'NVDA'),
            ('Close',  'TSLA'),
            ('Close',     'V'),
            ( 'High',  'AAPL')],
           names=['Price', 'Ticker'])

In [26]:
import numpy as np
import pandas as pd
today = np.datetime64("now", "D")
previous_business_day = np.busday_offset(today, -1, roll="backward")
start_time = pd.Timestamp(previous_business_day)
min_data = yf.download(tickers="AAPL", interval="1m", start=start_time)
min_data

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
Datetime,,,,,
2026-01-16 14:30:00+00:00,258.519989,258.649994,258.049988,258.200012,7058553
2026-01-16 14:31:00+00:00,258.700012,258.829987,258.200012,258.510010,135919
2026-01-16 14:32:00+00:00,258.380005,258.690002,258.350006,258.654999,80636
2026-01-16 14:33:00+00:00,258.720001,258.730011,258.170013,258.350006,70961
2026-01-16 14:34:00+00:00,258.329987,258.899994,258.290009,258.709991,154933
...,...,...,...,...,...
2026-01-16 20:55:00+00:00,255.380005,255.682999,255.330002,255.399994,263984
2026-01-16 20:56:00+00:00,255.539993,255.619995,255.339996,255.380005,188339
2026-01-16 20:57:00+00:00,255.509995,255.675003,255.449997,255.529999,206756
2026-01-16 20:58:00+00:00,255.770004,255.830002,255.470001,255.520004,283795
2026-01-16 20:59:00+00:00,255.479996,255.880005,255.449997,255.830002,474896

In [9]:
min_data = yf.download(tickers="AAPL", interval="1m", period='5d')
min_data

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
Datetime,,,,,
2026-01-12 14:30:00+00:00,259.709991,259.989990,259.029999,259.410004,2117787
2026-01-12 14:31:00+00:00,259.954987,260.269989,259.350006,259.546509,462096
2026-01-12 14:32:00+00:00,259.029999,260.000000,259.029999,259.934998,103142
2026-01-12 14:33:00+00:00,258.579987,259.160004,258.220001,259.160004,141972
2026-01-12 14:34:00+00:00,258.029999,258.660004,257.920013,258.540009,129260
...,...,...,...,...,...
2026-01-16 20:55:00+00:00,255.380005,255.682999,255.330002,255.399994,263984
2026-01-16 20:56:00+00:00,255.539993,255.619995,255.339996,255.380005,188339
2026-01-16 20:57:00+00:00,255.509995,255.675003,255.449997,255.529999,206756
2026-01-16 20:58:00+00:00,255.770004,255.830002,255.470001,255.520004,283795
2026-01-16 20:59:00+00:00,255.479996,255.880005,255.449997,255.830002,474896

In [ ]:
# crypto daily bars
univ = ['BTC-USD','ETH-USD','BNB-USD','ADA-USD','LINK-USD','XRP-USD','XLM-USD','DOGE-USD','AVAX-USD']
crypto_px = yf.download(univ, start="2019-01-01")

In [ ]:
crypto_px['Close']['BTC-USD'].plot()

In [ ]:
crypto_px.to_pickle('crypto_px.pk')

In [ ]:
pd.read_pickle('crypto_px.pk')

# Kraken Downloadable CSV
https://support.kraken.com/hc/en-us/articles/360047124832-Downloadable-historical-OHLCVT-Open-High-Low-Close-Volume-Trades-data

# Binance API for more crypto coins and minute bar data
1. Install python-binance: pip install python-binance
2. Documentation: https://python-binance.readthedocs.io/en/latest/
3. GitHub: https://github.com/sammchardy/python-binance

In [ ]:
from binance.client import Client
binance_client = Client()
px = binance_client.get_klines(symbol="BTCUSDT", interval="1h", limit=5)
print(len(px), px[:1])

In [ ]:
px

In [20]:
def format_binance(data):
    columns = ['open_time','open','high','low','close','volume','close_time','quote_volume',
    'num_trades','taker_base_volume','taker_quote_volume','ignore']

    data = pd.DataFrame(data,columns = columns)
    
    # Convert from POSIX timestamp (number of millisecond since jan 1, 1970)
    data['open_time'] = data['open_time'].map(lambda x: datetime.fromtimestamp(x/1000))
    data['close_time'] = data['close_time'].map(lambda x: datetime.fromtimestamp(x/1000))
    return data

In [21]:
format_binance(px)

,open_time,open,high,low,close,volume,close_time,quote_volume,num_trades,taker_base_volume,taker_quote_volume,ignore
0,2026-01-19 09:00:00,93673.14000000,93673.14000000,91910.20000000,92711.02000000,4221.82713000,2026-01-19 09:59:59.999,391410938.63318060,702026,2013.05803000,186611115.75122240,0
1,2026-01-19 10:00:00,92711.02000000,92875.68000000,92247.97000000,92586.65000000,910.87085000,2026-01-19 10:59:59.999,84357357.54796400,269217,496.52291000,45989922.49763250,0
2,2026-01-19 11:00:00,92586.65000000,92672.00000000,92383.94000000,92566.80000000,452.44264000,2026-01-19 11:59:59.999,41866839.32398060,123754,241.18739000,22320939.61663930,0
3,2026-01-19 12:00:00,92566.80000000,92776.83000000,92500.00000000,92690.09000000,556.40187000,2026-01-19 12:59:59.999,51547488.41051060,95858,357.82667000,33152814.73303800,0
4,2026-01-19 13:00:00,92690.08000000,92748.32000000,92502.58000000,92646.57000000,309.31325000,2026-01-19 13:59:59.999,28656303.38229230,50886,168.58792000,15618420.97922080,0

In [22]:
# get all the historical data
px = format_binance(client.get_historical_klines('BTCUSDT','1d',0))

In [23]:
px

,open_time,open,high,low,close,volume,close_time,quote_volume,num_trades,taker_base_volume,taker_quote_volume,ignore
0,2017-08-17 09:00:00,4261.48000000,4485.39000000,4200.74000000,4285.08000000,795.15037700,2017-08-18 08:59:59.999,3454770.05073206,3427,616.24854100,2678216.40060401,0
1,2017-08-18 09:00:00,4285.08000000,4371.52000000,3938.77000000,4108.37000000,1199.88826400,2017-08-19 08:59:59.999,5086958.30617151,5233,972.86871000,4129123.31651808,0
2,2017-08-19 09:00:00,4108.37000000,4184.69000000,3850.00000000,4139.98000000,381.30976300,2017-08-20 08:59:59.999,1549483.73542151,2153,274.33604200,1118001.87008735,0
3,2017-08-20 09:00:00,4120.98000000,4211.08000000,4032.62000000,4086.29000000,467.08302200,2017-08-21 08:59:59.999,1930364.39032646,2321,376.79594700,1557401.33373730,0
4,2017-08-21 09:00:00,4069.13000000,4119.62000000,3911.79000000,4016.00000000,691.74306000,2017-08-22 08:59:59.999,2797231.71402728,3972,557.35610700,2255662.55315837,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3073,2026-01-15 09:00:00,96951.78000000,97193.34000000,95134.48000000,95604.80000000,21725.81369000,2026-01-16 08:59:59.999,2093008182.84373360,4493095,10841.32767000,1045103063.11148480,0
3074,2026-01-16 09:00:00,95604.81000000,95871.47000000,94293.46000000,95550.94000000,11167.71460000,2026-01-17 08:59:59.999,1064019408.07725140,2971559,5055.06952000,481723178.08146790,0
3075,2026-01-17 09:00:00,95550.94000000,95639.45000000,95021.67000000,95147.77000000,4280.80137000,2026-01-18 08:59:59.999,408161941.67190790,1020527,2059.85283000,196399075.97097010,0
3076,2026-01-18 09:00:00,95147.77000000,95531.12000000,93615.40000000,93673.14000000,6895.17819000,2026-01-19 08:59:59.999,654773743.26771180,1488785,3107.35604000,295217762.82127930,0
3077,2026-01-19 09:00:00,93673.14000000,93673.14000000,91910.20000000,92571.27000000,6465.78769000,2026-01-20 08:59:59.999,599221860.44186780,1244533,3279.07579000,303868427.05803420,0

In [24]:
# interval strings
client.KLINE_INTERVAL_1MINUTE

'1m'

In [47]:
# Get minute bar data
start_string = np.datetime_as_string(today).replace("T", " ")
### px = binance_client.get_historical_klines('BTCUSDT','1m','2026-01-19 00:00:00')
px = binance_client.get_historical_klines('BTCUSDT','1m',start_string)
print(px)

[[1768780800000, '93673.14000000', '93673.14000000', '93340.34000000', '93365.03000000', '240.21087000', 1768780859999, '22460332.18835160', 22004, '37.39972000', '3495409.24272870', '0'], [1768780860000, '93365.03000000', '93365.04000000', '92789.84000000', '92792.20000000', '409.77554000', 1768780919999, '38157723.51772300', 35329, '129.22359000', '12036777.16448020', '0'], [1768780920000, '92792.19000000', '92887.62000000', '92164.46000000', '92209.91000000', '373.28347000', 1768780979999, '34544118.21173000', 35446, '130.37273000', '12063887.69388640', '0'], [1768780980000, '92209.91000000', '92827.36000000', '91910.20000000', '92793.11000000', '406.71164000', 1768781039999, '37518719.40000310', 40905, '180.38052000', '16652212.63506950', '0'], [1768781040000, '92793.11000000', '93088.23000000', '92771.73000000', '92977.70000000', '142.50063000', 1768781099999, '13242675.30461840', 22703, '82.00953000', '7621151.14290860', '0'], [1768781100000, '92977.70000000', '93129.88000000', '92954.84000000', '93035.83000000', '96.30247000', 1768781159999, '8960303.22780880', 17233, '68.67140000', '6389504.27425080', '0'], [1768781160000, '93035.83000000', '93072.75000000', '92692.38000000', '92749.79000000', '86.99175000', 1768781219999, '8077491.25387190', 16550, '30.33696000', '2817040.62177790', '0'], [1768781220000, '92749.80000000', '92897.18000000', '92665.17000000', '92865.85000000', '93.25311000', 1768781279999, '8655240.35393360', 16485, '60.45751000', '5611271.83400000', '0'], [1768781280000, '92865.85000000', '93037.17000000', '92843.53000000', '92989.09000000', '179.51454000', 1768781339999, '16679897.91955930', 15949, '136.92842000', '12721607.71652050', '0'], [1768781340000, '92989.09000000', '93004.85000000', '92868.66000000', '92881.51000000', '39.43974000', 1768781399999, '3664863.71713250', 9007, '8.92323000', '829247.58375830', '0'], [1768781400000, '92881.52000000', '92894.16000000', '92701.80000000', '92715.15000000', '115.93978000', 1768781459999, '10756740.60193530', 9497, '36.66515000', '3403156.23937820', '0'], [1768781460000, '92715.15000000', '92744.00000000', '92578.45000000', '92628.91000000', '42.86487000', 1768781519999, '3971166.22079750', 13825, '18.76156000', '1738049.37452640', '0'], [1768781520000, '92628.90000000', '92796.67000000', '92576.92000000', '92785.08000000', '40.97114000', 1768781579999, '3797693.32930720', 11885, '29.58768000', '2742576.73406390', '0'], [1768781580000, '92785.08000000', '92805.57000000', '92684.37000000', '92701.86000000', '81.05256000', 1768781639999, '7516301.25482900', 9581, '61.39395000', '5692781.14212860', '0'], [1768781640000, '92701.87000000', '92715.94000000', '92377.65000000', '92448.61000000', '62.16952000', 1768781699999, '5750536.60938730', 16420, '24.07747000', '2226921.11069050', '0'], [1768781700000, '92448.61000000', '92466.05000000', '92222.76000000', '92279.65000000', '102.42267000', 1768781759999, '9456059.58353340', 23075, '35.31171000', '3260395.70443740', '0'], [1768781760000, '92279.65000000', '92482.04000000', '92125.30000000', '92441.52000000', '141.09554000', 1768781819999, '13011036.55848420', 23632, '49.25472000', '4544378.21653490', '0'], [1768781820000, '92441.53000000', '92711.36000000', '92299.20000000', '92711.36000000', '121.11916000', 1768781879999, '11204725.51875080', 18149, '68.58633000', '6346702.45219820', '0'], [1768781880000, '92711.36000000', '92716.09000000', '92484.01000000', '92650.00000000', '22.01724000', 1768781939999, '2038461.25093980', 10974, '10.61024000', '982383.91072310', '0'], [1768781940000, '92650.00000000', '92815.57000000', '92634.46000000', '92792.38000000', '51.48195000', 1768781999999, '4774919.07002850', 12081, '37.08162000', '3439094.00825950', '0'], [1768782000000, '92792.38000000', '92792.38000000', '92354.63000000', '92366.21000000', '43.49892000', 1768782059999, '4024318.84048040', 12275, '10.85794000', '1004287.52031080', '0'], [1768782060000, '92366.21000000', '92450.00000000', '92250.00000000', '92322.13000000', '60.39968000', 1768782119999, '5576142.42711190', 15686, '25.27539000', '2333490.75045270', '0'], [1768782120000, '92322.13000000', '92497.72000000', '92257.96000000', '92394.21000000', '46.66224000', 1768782179999, '4309772.40263230', 15317, '19.56798000', '1807137.47509480', '0'], [1768782180000, '92394.21000000', '92716.00000000', '92378.35000000', '92576.08000000', '210.70161000', 1768782239999, '19508262.63368370', 14631, '104.09166000', '9639825.98051970', '0'], [1768782240000, '92576.08000000', '92635.00000000', '92540.00000000', '92604.88000000', '18.92118000', 1768782299999, '1751650.55973040', 8689, '10.08319000', '933469.75442400', '0'], [1768782300000, '92604.88000000', '92604.88000000', '92356.27000000', '92528.24000000', '39.47073000', 1768782359999, '3648537.30909220', 12216, '27.06553000', '2501601.45016320', '0'], [1768782360000, '92528.23000000', '92638.25000000', '92473.20000000', '92620.64000000', '71.26288000', 1768782419999, '6596377.36784230', 8462, '53.41525000', '4944034.60812450', '0'], [1768782420000, '92620.64000000', '92620.64000000', '92500.00000000', '92540.52000000', '27.31392000', 1768782479999, '2528180.75647620', 7907, '18.19554000', '1684037.14010850', '0'], [1768782480000, '92540.52000000', '92629.04000000', '92465.71000000', '92622.54000000', '32.92424000', 1768782539999, '3046573.55604650', 9026, '22.01574000', '2037158.58691980', '0'], [1768782540000, '92622.54000000', '92722.09000000', '92613.27000000', '92638.36000000', '47.51599000', 1768782599999, '4403096.22122710', 8180, '27.29074000', '2528726.36593080', '0'], [1768782600000, '92638.35000000', '92638.35000000', '92269.55000000', '92360.00000000', '51.41390000', 1768782659999, '4750945.47452680', 15138, '18.86050000', '1742873.15165100', '0'], [1768782660000, '92360.00000000', '92520.00000000', '92326.14000000', '92440.00000000', '30.42243000', 1768782719999, '2811651.01409080', 11969, '21.61202000', '1997387.10311670', '0'], [1768782720000, '92440.00000000', '92666.87000000', '92410.00000000', '92599.91000000', '53.96530000', 1768782779999, '4997002.59711180', 10802, '43.49256000', '4027497.21323060', '0'], [1768782780000, '92599.91000000', '92669.67000000', '92511.60000000', '92651.57000000', '27.47905000', 1768782839999, '2544852.23746730', 9503, '12.22754000', '1132329.72715990', '0'], [1768782840000, '92651.56000000', '92651.57000000', '92532.87000000', '92554.33000000', '27.68130000', 1768782899999, '2563071.13153210', 8596, '16.49060000', '1526629.41238640', '0'], [1768782900000, '92554.33000000', '92587.07000000', '92467.64000000', '92526.70000000', '39.42791000', 1768782959999, '3647590.39889500', 7779, '19.77719000', '1829577.87530120', '0'], [1768782960000, '92526.70000000', '92625.15000000', '92526.70000000', '92562.62000000', '24.75784000', 1768783019999, '2291987.20068060', 7769, '16.79456000', '1554700.05384840', '0'], [1768783020000, '92562.62000000', '92626.27000000', '92513.99000000', '92626.27000000', '15.73046000', 1768783079999, '1456235.40288430', 6776, '11.00602000', '1018860.01504400', '0'], [1768783080000, '92626.26000000', '92904.44000000', '92617.00000000', '92810.11000000', '84.09866000', 1768783139999, '7804852.41062470', 17786, '68.06726000', '6317659.07301780', '0'], [1768783140000, '92810.10000000', '92863.13000000', '92757.36000000', '92839.48000000', '37.64552000', 1768783199999, '3494638.56976900', 7938, '10.51561000', '976071.78350190', '0'], [1768783200000, '92839.48000000', '92847.78000000', '92734.63000000', '92847.78000000', '22.77870000', 1768783259999, '2113886.96019140', 7682, '9.85857000', '914770.58523570', '0'], [1768783260000, '92847.78000000', '92899.34000000', '92818.46000000', '92840.65000000', '42.75318000', 1768783319999, '3969815.51162130', 7956, '22.84482000', '2121284.52250830', '0'], [1768783320000, '92840.65000000', '93050.52000000', '92816.00000000', '93016.24000000', '60.48190000', 1768783379999, '5621299.75681920', 11267, '37.71565000', '3505941.49919630', '0'], [1768783380000, '93016.24000000', '93035.64000000', '92955.49000000', '92982.65000000', '30.36334000', 1768783439999, '2823937.29548970', 7754, '20.11343000', '1870663.59881360', '0'], [1768783440000, '92982.64000000', '92997.22000000', '92955.03000000', '92977.88000000', '12.60141000', 1768783499999, '1171548.19021550', 3214, '6.83303000', '635270.52171440', '0'], [1768783500000, '92977.89000000', '92977.89000000', '92816.00000000', '92896.66000000', '67.16526000', 1768783559999, '6238176.20980630', 10274, '46.94262000', '4359881.71367250', '0'], [1768783560000, '92896.65000000', '92896.66000000', '92817.32000000', '92896.66000000', '12.97984000', 1768783619999, '1205305.69620320', 5524, '6.09689000', '566142.24376250', '0'], [1768783620000, '92896.65000000', '92924.79000000', '92815.22000000', '92827.28000000', '10.93450000', 1768783679999, '1015644.31082960', 4908, '4.94716000', '459425.51059640', '0'], [1768783680000, '92827.27000000', '92839.96000000', '92760.00000000', '92760.00000000', '16.05012000', 1768783739999, '1489661.87262530', 6272, '4.29322000', '398477.58247240', '0'], [1768783740000, '92760.01000000', '92872.78000000', '92760.00000000', '92872.78000000', '10.59728000', 1768783799999, '983409.20332270', 5566, '8.02666000', '744828.28482010', '0'], [1768783800000, '92872.78000000', '92872.78000000', '92763.46000000', '92763.48000000', '8.30594000', 1768783859999, '770725.30791010', 4131, '4.38744000', '407072.05962970', '0'], [1768783860000, '92763.47000000', '92772.17000000', '92713.45000000', '92730.60000000', '12.39070000', 1768783919999, '1149188.59280640', 3053, '5.81546000', '539310.55784350', '0'], [1768783920000, '92730.59000000', '92775.62000000', '92700.48000000', '92775.62000000', '11.49808000', 1768783979999, '1066203.38639740', 4067, '4.47599000', '415093.05043330', '0'], [1768783980000, '92775.62000000', '92775.62000000', '92712.84000000', '92718.82000000', '15.19565000', 1768784039999, '1409197.64030420', 3587, '4.28989000', '397774.18378430', '0'], [1768784040000, '92718.82000000', '92796.00000000', '92715.00000000', '92769.99000000', '6.74523000', 1768784099999, '625611.13883420', 4189, '5.05523000', '468840.24303240', '0'], [1768784100000, '92769.99000000', '92769.99000000', '92706.43000000', '92708.38000000', '5.60046000', 1768784159999, '519316.48211740', 2709, '2.45985000', '228087.93323310', '0'], [1768784160000, '92708.39000000', '92804.45000000', '92708.38000000', '92727.14000000', '10.34163000', 1768784219999, '959166.60572340', 3485, '7.62674000', '707303.11313970', '0'], [1768784220000, '92727.14000000', '92773.54000000', '92713.76000000', '92726.93000000', '7.08946000', 1768784279999, '657508.35711220', 3702, '5.47305000', '507599.98443090', '0'], [1768784280000, '92726.93000000', '92740.55000000', '92714.64000000', '92714.65000000', '14.11519000', 1768784339999, '1308815.21596540', 3404, '10.63503000', '986098.12917380', '0'], [1768784340000, '92714.64000000', '92726.86000000', '92711.01000000', '92711.02000000', '3.42731000', 1768784399999, '317777.29425510', 2107, '2.43044000', '225346.59110120', '0'], [1768784400000, '92711.02000000', '92711.02000000', '92504.00000000', '92600.00000000', '35.87556000', 1768784459999, '3321719.52410810', 13017, '14.14084000', '1309225.83223550', '0'], [1768784460000, '92600.00000000', '92670.08000000', '92562.44000000', '92603.01000000', '17.88430000', 1768784519999, '1656290.43434740', 9005, '7.87588000', '729424.45616230', '0'], [1768784520000, '92603.02000000', '92650.00000000', '92575.95000000', '92637.26000000', '11.67928000', 1768784579999, '1081658.58267150', 5429, '7.54917000', '699171.21939050', '0'], [1768784580000, '92637.26000000', '92678.63000000', '92609.39000000', '92638.31000000', '9.60979000', 1768784639999, '890212.49176540', 4266, '3.61337000', '334725.95595230', '0'], [1768784640000, '92638.32000000', '92664.97000000', '92612.18000000', '92630.33000000', '11.10764000', 1768784699999, '1028933.04523730', 5480, '2.58138000', '239119.55650090', '0'], [1768784700000, '92630.34000000', '92667.75000000', '92588.92000000', '92667.74000000', '14.30764000', 1768784759999, '1325217.83386790', 3491, '9.78208000', '905984.98618060', '0'], [1768784760000, '92667.74000000', '92788.93000000', '92661.05000000', '92778.11000000', '36.51251000', 1768784819999, '3386703.61710530', 5528, '31.91806000', '2960607.14239580', '0'], [1768784820000, '92778.11000000', '92778.11000000', '92654.19000000', '92698.96000000', '11.77054000', 1768784879999, '1091139.26602930', 5077, '5.04594000', '467715.43713090', '0'], [1768784880000, '92698.95000000', '92778.07000000', '92680.03000000', '92728.92000000', '14.81253000', 1768784939999, '1373565.61705370', 4574, '10.83202000', '1004434.66460410', '0'], [1768784940000, '92728.92000000', '92816.25000000', '92715.91000000', '92781.29000000', '17.29104000', 1768784999999, '1604229.06693700', 4851, '12.95931000', '1202341.17430550', '0'], [1768785000000, '92781.29000000', '92782.00000000', '92725.66000000', '92757.79000000', '11.70228000', 1768785059999, '1085384.71135580', 6009, '5.57515000', '517067.49204940', '0'], [1768785060000, '92757.79000000', '92809.21000000', '92744.67000000', '92805.77000000', '45.18668000', 1768785119999, '4192248.86212900', 3452, '37.12554000', '3444433.08946690', '0'], [1768785120000, '92805.77000000', '92861.41000000', '92789.86000000', '92861.41000000', '18.04044000', 1768785179999, '1674522.56314510', 5224, '15.85005000', '1471212.56333320', '0'], [1768785180000, '92861.40000000', '92861.41000000', '92760.91000000', '92760.91000000', '26.31090000', 1768785239999, '2441799.99630500', 3684, '8.30485000', '770721.61059470', '0'], [1768785240000, '92760.91000000', '92776.57000000', '92757.79000000', '92757.79000000', '10.24607000', 1768785299999, '950525.49728920', 2742, '6.49509000', '602539.91428400', '0'], [1768785300000, '92757.79000000', '92795.50000000', '92722.01000000', '92722.01000000', '38.95334000', 1768785359999, '3613336.74420290', 5630, '26.00029000', '2411824.26919420', '0'], [1768785360000, '92722.01000000', '92822.21000000', '92722.00000000', '92822.21000000', '9.60131000', 1768785419999, '890895.09811060', 3993, '4.61663000', '428357.79118140', '0'], [1768785420000, '92822.21000000', '92822.21000000', '92800.12000000', '92817.95000000', '5.54214000', 1768785479999, '514378.01816160', 1711, '2.94434000', '273264.40738840', '0'], [1768785480000, '92817.96000000', '92875.68000000', '92761.48000000', '92761.49000000', '11.13757000', 1768785539999, '1033970.74539100', 5451, '6.48998000', '602481.31653760', '0'], [1768785540000, '92761.49000000', '92778.00000000', '92722.00000000', '92778.00000000', '7.32588000', 1768785599999, '679421.65286150', 4432, '5.09806000', '472793.34250650', '0'], [1768785600000, '92777.99000000', '92778.00000000', '92702.12000000', '92702.13000000', '37.11988000', 1768785659999, '3442183.47336660', 4022, '17.76118000', '1646760.52281550', '0'], [1768785660000, '92702.13000000', '92702.13000000', '92602.20000000', '92614.95000000', '22.20542000', 1768785719999, '2057329.74126100', 3035, '7.46144000', '691107.20085370', '0'], [1768785720000, '92614.95000000', '92700.00000000', '92576.59000000', '92684.60000000', '18.69243000', 1768785779999, '1731537.29998530', 5143, '12.21838000', '1131798.34453200', '0'], [1768785780000, '92684.60000000', '92704.91000000', '92607.56000000', '92634.12000000', '6.82720000', 1768785839999, '632478.11299200', 3542, '2.33795000', '216564.58402560', '0'], [1768785840000, '92634.13000000', '92659.28000000', '92600.00000000', '92646.15000000', '5.29165000', 1768785899999, '490135.81609860', 3802, '3.11262000', '288289.23463890', '0'], [1768785900000, '92646.14000000', '92646.15000000', '92600.27000000', '92606.90000000', '25.81810000', 1768785959999, '2391116.44179730', 2264, '4.76582000', '441384.35645990', '0'], [1768785960000, '92606.90000000', '92644.59000000', '92606.90000000', '92632.83000000', '8.92516000', 1768786019999, '826619.40840170', 2384, '5.88798000', '545297.01456260', '0'], [1768786020000, '92632.84000000', '92646.59000000', '92590.82000000', '92625.51000000', '8.42218000', 1768786079999, '780001.10871350', 3158, '2.42650000', '224744.53091660', '0'], [1768786080000, '92625.51000000', '92644.51000000', '92595.23000000', '92621.97000000', '12.56932000', 1768786139999, '1164197.08977190', 3039, '4.48301000', '415206.15190210', '0'], [1768786140000, '92621.96000000', '92631.90000000', '92564.41000000', '92564.42000000', '7.88378000', 1768786199999, '729921.18495680', 2581, '1.77256000', '164093.58686210', '0'], [1768786200000, '92564.41000000', '92646.89000000', '92547.00000000', '92547.01000000', '9.50394000', 1768786259999, '879975.12712550', 6643, '4.58951000', '424945.58763650', '0'], [1768786260000, '92547.00000000', '92621.93000000', '92518.54000000', '92621.93000000', '10.32122000', 1768786319999, '955505.65623020', 5149, '5.67887000', '525741.76441390', '0'], [1768786320000, '92621.92000000', '92688.00000000', '92621.92000000', '92678.64000000', '15.54001000', 1768786379999, '1439889.28269930', 4935, '10.18545000', '943760.53076440', '0'], [1768786380000, '92678.64000000', '92678.64000000', '92602.83000000', '92620.30000000', '8.73454000', 1768786439999, '809187.68599240', 3586, '2.84920000', '263909.75204380', '0'], [1768786440000, '92620.31000000', '92735.54000000', '92620.31000000', '92725.77000000', '8.68091000', 1768786499999, '804743.45191330', 4011, '5.44776000', '504941.07796650', '0'], [1768786500000, '92725.77000000', '92725.77000000', '92685.40000000', '92685.41000000', '3.32233000', 1768786559999, '307965.58562620', 1624, '0.89565000', '83021.02528440', '0'], [1768786560000, '92685.41000000', '92720.25000000', '92654.19000000', '92720.25000000', '6.35687000', 1768786619999, '589124.44491890', 4377, '3.64151000', '337454.07990820', '0'], [1768786620000, '92720.25000000', '92753.06000000', '92714.16000000', '92748.40000000', '8.76481000', 1768786679999, '812776.81649860', 2984, '3.66575000', '339927.07226570', '0'], [1768786680000, '92748.40000000', '92789.04000000', '92710.59000000', '92710.59000000', '17.31042000', 1768786739999, '1605626.03642040', 4847, '13.85159000', '1284775.82051460', '0'], [1768786740000, '92710.37000000', '92710.38000000', '92600.00000000', '92646.00000000', '13.72738000', 1768786799999, '1271817.46451280', 4581, '4.01830000', '372250.62123890', '0'], [1768786800000, '92645.99000000', '92675.95000000', '92624.97000000', '92655.02000000', '3.89059000', 1768786859999, '360465.81005280', 2532, '1.94746000', '180428.43893850', '0'], [1768786860000, '92655.01000000', '92685.78000000', '92614.00000000', '92614.00000000', '11.05616000', 1768786919999, '1024409.46547560', 4282, '8.07810000', '748483.00858450', '0'], [1768786920000, '92614.00000000', '92624.01000000', '92550.58000000', '92564.37000000', '9.24842000', 1768786979999, '856208.02923870', 2990, '4.73262000', '438070.92067620', '0'], [1768786980000, '92564.37000000', '92575.16000000', '92561.73000000', '92561.73000000', '5.20004000', 1768787039999, '481341.67638530', 1702, '1.69527000', '156921.33176320', '0'], [1768787040000, '92561.73000000', '92561.74000000', '92518.54000000', '92518.54000000', '14.93925000', 1768787099999, '1382561.40670310', 2842, '2.53428000', '234522.62325440', '0'], [1768787100000, '92518.55000000', '92518.55000000', '92484.00000000', '92484.01000000', '13.57278000', 1768787159999, '1255510.42529700', 4143, '2.45071000', '226691.98109580', '0'], [1768787160000, '92484.00000000', '92489.62000000', '92417.79000000', '92428.77000000', '16.70892000', 1768787219999, '1544725.45556330', 8485, '6.31643000', '583913.43723450', '0'], [1768787220000, '92428.76000000', '92486.00000000', '92373.64000000', '92376.67000000', '19.91314000', 1768787279999, '1840860.60928680', 5614, '11.80332000', '1091298.52557700', '0'], [1768787280000, '92376.67000000', '92394.67000000', '92257.00000000', '92309.23000000', '33.41991000', 1768787339999, '3

/var/folders/n9/h8rhghm93t97qffmcf8qqbqr0000gn/T/ipykernel_3430/3850776428.py:4: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.
See https://github.com/python/cpython/issues/70647.
  px = binance_client.get_historical_klines('BTCUSDT','1m',start_string)

In [48]:
px = format_binance(px)
px

,open_time,open,high,low,close,volume,close_time,quote_volume,num_trades,taker_base_volume,taker_quote_volume,ignore
0,2026-01-19 09:00:00,93673.14000000,93673.14000000,93340.34000000,93365.03000000,240.21087000,2026-01-19 09:00:59.999,22460332.18835160,22004,37.39972000,3495409.24272870,0
1,2026-01-19 09:01:00,93365.03000000,93365.04000000,92789.84000000,92792.20000000,409.77554000,2026-01-19 09:01:59.999,38157723.51772300,35329,129.22359000,12036777.16448020,0
2,2026-01-19 09:02:00,92792.19000000,92887.62000000,92164.46000000,92209.91000000,373.28347000,2026-01-19 09:02:59.999,34544118.21173000,35446,130.37273000,12063887.69388640,0
3,2026-01-19 09:03:00,92209.91000000,92827.36000000,91910.20000000,92793.11000000,406.71164000,2026-01-19 09:03:59.999,37518719.40000310,40905,180.38052000,16652212.63506950,0
4,2026-01-19 09:04:00,92793.11000000,93088.23000000,92771.73000000,92977.70000000,142.50063000,2026-01-19 09:04:59.999,13242675.30461840,22703,82.00953000,7621151.14290860,0
...,...,...,...,...,...,...,...,...,...,...,...,...
294,2026-01-19 13:54:00,92702.11000000,92720.62000000,92702.10000000,92720.61000000,1.77928000,2026-01-19 13:54:59.999,164958.20545350,631,1.28044000,118712.31605150,0
295,2026-01-19 13:55:00,92720.62000000,92720.62000000,92720.61000000,92720.61000000,0.64709000,2026-01-19 13:55:59.999,59998.58203540,171,0.25105000,23277.51165100,0
296,2026-01-19 13:56:00,92720.61000000,92720.62000000,92720.61000000,92720.62000000,2.07252000,2026-01-19 13:56:59.999,192165.33471400,218,1.60768000,149065.08636160,0
297,2026-01-19 13:57:00,92720.61000000,92742.65000000,92699.93000000,92699.93000000,14.98417000,2026-01-19 13:57:59.999,1389430.79544590,1946,8.63209000,800392.13185520,0
298,2026-01-19 13:58:00,92699.94000000,92699.94000000,92693.93000000,92693.93000000,3.40971000,2026-01-19 13:58:59.999,316070.23472670,357,2.41502000,223863.68891880,0

In [3]:
px.to_pickle('BINANCE_BTCUSDT_1M.pk')

NameError: name 'px' is not defined

In [50]:
pd.read_pickle('BINANCE_BTCUSDT_1M.pk')

,open_time,open,high,low,close,volume,close_time,quote_volume,num_trades,taker_base_volume,taker_quote_volume,ignore
0,2026-01-19 09:00:00,93673.14000000,93673.14000000,93340.34000000,93365.03000000,240.21087000,2026-01-19 09:00:59.999,22460332.18835160,22004,37.39972000,3495409.24272870,0
1,2026-01-19 09:01:00,93365.03000000,93365.04000000,92789.84000000,92792.20000000,409.77554000,2026-01-19 09:01:59.999,38157723.51772300,35329,129.22359000,12036777.16448020,0
2,2026-01-19 09:02:00,92792.19000000,92887.62000000,92164.46000000,92209.91000000,373.28347000,2026-01-19 09:02:59.999,34544118.21173000,35446,130.37273000,12063887.69388640,0
3,2026-01-19 09:03:00,92209.91000000,92827.36000000,91910.20000000,92793.11000000,406.71164000,2026-01-19 09:03:59.999,37518719.40000310,40905,180.38052000,16652212.63506950,0
4,2026-01-19 09:04:00,92793.11000000,93088.23000000,92771.73000000,92977.70000000,142.50063000,2026-01-19 09:04:59.999,13242675.30461840,22703,82.00953000,7621151.14290860,0
...,...,...,...,...,...,...,...,...,...,...,...,...
294,2026-01-19 13:54:00,92702.11000000,92720.62000000,92702.10000000,92720.61000000,1.77928000,2026-01-19 13:54:59.999,164958.20545350,631,1.28044000,118712.31605150,0
295,2026-01-19 13:55:00,92720.62000000,92720.62000000,92720.61000000,92720.61000000,0.64709000,2026-01-19 13:55:59.999,59998.58203540,171,0.25105000,23277.51165100,0
296,2026-01-19 13:56:00,92720.61000000,92720.62000000,92720.61000000,92720.62000000,2.07252000,2026-01-19 13:56:59.999,192165.33471400,218,1.60768000,149065.08636160,0
297,2026-01-19 13:57:00,92720.61000000,92742.65000000,92699.93000000,92699.93000000,14.98417000,2026-01-19 13:57:59.999,1389430.79544590,1946,8.63209000,800392.13185520,0
298,2026-01-19 13:58:00,92699.94000000,92699.94000000,92693.93000000,92693.93000000,3.40971000,2026-01-19 13:58:59.999,316070.23472670,357,2.41502000,223863.68891880,0

# Other
- We will add to this as class goes on (pandas datareader, ccxt, quandl, simfin)